complete -c pepsi -n "__fish_use_subcommand" -l repository-root -d 'Alternative repository root (if not given the parent of .git is used)' -r -F
complete -c pepsi -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_use_subcommand" -f -a "analyze" -d 'Analyze source code'
complete -c pepsi -n "__fish_use_subcommand" -f -a "aliveness" -d 'Get aliveness information from NAOs'
complete -c pepsi -n "__fish_use_subcommand" -f -a "build" -d 'Builds the code for a target'
complete -c pepsi -n "__fish_use_subcommand" -f -a "check" -d 'Checks the code with cargo check'
complete -c pepsi -n "__fish_use_subcommand" -f -a "clippy" -d 'Checks the code with cargo clippy'
complete -c pepsi -n "__fish_use_subcommand" -f -a "communication" -d 'Enable/disable communication'
complete -c pepsi -n "__fish_use_subcommand" -f -a "completions" -d 'Generates shell completion files'
complete -c pepsi -n "__fish_use_subcommand" -f -a "gammaray" -d 'Flash a HULKs-OS image to NAOs'
complete -c pepsi -n "__fish_use_subcommand" -f -a "hulk" -d 'Control the HULK service'
complete -c pepsi -n "__fish_use_subcommand" -f -a "location" -d 'Control the configured location'
complete -c pepsi -n "__fish_use_subcommand" -f -a "logs" -d 'Logging on the NAO'
complete -c pepsi -n "__fish_use_subcommand" -f -a "playernumber" -d 'Change player numbers of the NAOs in local parameters'
complete -c pepsi -n "__fish_use_subcommand" -f -a "ping" -d 'Ping NAOs'
complete -c pepsi -n "__fish_use_subcommand" -f -a "postgame" -d 'Disable NAOs after a game (downloads logs, unsets wireless network, etc.)'
complete -c pepsi -n "__fish_use_subcommand" -f -a "poweroff" -d 'Power NAOs off'
complete -c pepsi -n "__fish_use_subcommand" -f -a "pregame" -d 'Get NAOs ready for a game (sets player numbers, uploads, sets wireless network, etc.)'
complete -c pepsi -n "__fish_use_subcommand" -f -a "reboot" -d 'Reboot NAOs'
complete -c pepsi -n "__fish_use_subcommand" -f -a "recording" -d 'Set cycler instances to be recorded'
complete -c pepsi -n "__fish_use_subcommand" -f -a "run" -d 'Runs the code for a target'
complete -c pepsi -n "__fish_use_subcommand" -f -a "sdk" -d 'Manage the NAO SDK'
complete -c pepsi -n "__fish_use_subcommand" -f -a "shell" -d 'Opens a command line shell to a NAO'
complete -c pepsi -n "__fish_use_subcommand" -f -a "upload" -d 'Upload the code to NAOs'
complete -c pepsi -n "__fish_use_subcommand" -f -a "wireless" -d 'Control wireless network on the NAO'
complete -c pepsi -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest; and not __fish_seen_subcommand_from help" -f -a "dump-contexts"
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest; and not __fish_seen_subcommand_from help" -f -a "dump-latest"
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and __fish_seen_subcommand_from dump-contexts" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and __fish_seen_subcommand_from dump-latest" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest; and not __fish_seen_subcommand_from help" -f -a "dump-contexts"
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest; and not __fish_seen_subcommand_from help" -f -a "dump-latest"
complete -c pepsi -n "__fish_seen_subcommand_from analyze; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from aliveness" -s t -l timeout -d 'Timeout in ms for waiting for responses' -r
complete -c pepsi -n "__fish_seen_subcommand_from aliveness" -s v -l verbose -d 'Output verbose version of the aliveness information'
complete -c pepsi -n "__fish_seen_subcommand_from aliveness" -s j -l json -d 'Output aliveness information as json'
complete -c pepsi -n "__fish_seen_subcommand_from aliveness" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from build" -l profile -r
complete -c pepsi -n "__fish_seen_subcommand_from build" -l target -r
complete -c pepsi -n "__fish_seen_subcommand_from build" -l workspace -d 'Apply to entire workspace (only valid for build/check/clippy)'
complete -c pepsi -n "__fish_seen_subcommand_from build" -l no-sdk-installation
complete -c pepsi -n "__fish_seen_subcommand_from build" -l remote -d 'Use a remote machine for compilation, see ./scripts/remote for details'
complete -c pepsi -n "__fish_seen_subcommand_from build" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from check" -l profile -r
complete -c pepsi -n "__fish_seen_subcommand_from check" -l target -r
complete -c pepsi -n "__fish_seen_subcommand_from check" -l workspace -d 'Apply to entire workspace (only valid for build/check/clippy)'
complete -c pepsi -n "__fish_seen_subcommand_from check" -l no-sdk-installation
complete -c pepsi -n "__fish_seen_subcommand_from check" -l remote -d 'Use a remote machine for compilation, see ./scripts/remote for details'
complete -c pepsi -n "__fish_seen_subcommand_from check" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from clippy" -l profile -r
complete -c pepsi -n "__fish_seen_subcommand_from clippy" -l target -r
complete -c pepsi -n "__fish_seen_subcommand_from clippy" -l workspace -d 'Apply to entire workspace (only valid for build/check/clippy)'
complete -c pepsi -n "__fish_seen_subcommand_from clippy" -l no-sdk-installation
complete -c pepsi -n "__fish_seen_subcommand_from clippy" -l remote -d 'Use a remote machine for compilation, see ./scripts/remote for details'
complete -c pepsi -n "__fish_seen_subcommand_from clippy" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from help" -f -a "enable"
complete -c pepsi -n "__fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from help" -f -a "disable"
complete -c pepsi -n "__fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from communication; and __fish_seen_subcommand_from enable" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from communication; and __fish_seen_subcommand_from disable" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from communication; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from help" -f -a "enable"
complete -c pepsi -n "__fish_seen_subcommand_from communication; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from help" -f -a "disable"
complete -c pepsi -n "__fish_seen_subcommand_from communication; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from completions" -l complete-naos
complete -c pepsi -n "__fish_seen_subcommand_from completions" -l complete-assignments
complete -c pepsi -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from gammaray" -l image-path -d 'Alternative path to an image' -r -F
complete -c pepsi -n "__fish_seen_subcommand_from gammaray" -l os-version -d 'Alternative HULKs-OS version e.g. 3.3' -r
complete -c pepsi -n "__fish_seen_subcommand_from gammaray" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from hulk" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all available locations'
complete -c pepsi -n "__fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "set" -d 'Set location for repository'
complete -c pepsi -n "__fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "status" -d 'Get currently configured locations'
complete -c pepsi -n "__fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from location; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from location; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from location; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from location; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all available locations'
complete -c pepsi -n "__fish_seen_subcommand_from location; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "set" -d 'Set location for repository'
complete -c pepsi -n "__fish_seen_subcommand_from location; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "status" -d 'Get currently configured locations'
complete -c pepsi -n "__fish_seen_subcommand_from location; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete logs on the NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "download" -d 'Download logs from the NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "show" -d 'Show logs from NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from download" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete logs on the NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "download" -d 'Download logs from the NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "show" -d 'Show logs from NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from playernumber" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from ping" -l timeout-seconds -d 'Time in seconds after which ping is aborted' -r
complete -c pepsi -n "__fish_seen_subcommand_from ping" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from postgame" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from poweroff" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l profile -r
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l cycler-instances-to-be-recorded -d 'Cycler instances to record e.g. Control or VisionBottom (don\'t specify to disable recording)' -r
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l no-sdk-installation -d 'Do not update nor install SDK'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l no-build -d 'Do not build before uploading'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l no-restart -d 'Do not restart HULK nor HULA service after uploading'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l no-clean -d 'Do not remove existing remote files during uploading'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l with-communication -d 'Enable communication'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l skip-os-check -d 'Skip the OS version check'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -l remote -d 'Use a remote machine for compilation, see ./scripts/remote for details'
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from reboot" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from recording" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from run" -l profile -r
complete -c pepsi -n "__fish_seen_subcommand_from run" -l target -r
complete -c pepsi -n "__fish_seen_subcommand_from run" -l workspace -d 'Apply to entire workspace (only valid for build/check/clippy)'
complete -c pepsi -n "__fish_seen_subcommand_from run" -l no-sdk-installation
complete -c pepsi -n "__fish_seen_subcommand_from run" -l remote -d 'Use a remote machine for compilation, see ./scripts/remote for details'
complete -c pepsi -n "__fish_seen_subcommand_from run" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "install"
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from install" -l sdk-version -d 'Alternative SDK version e.g. 3.3' -r
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from install" -l installation-directory -d 'Alternative SDK installation directory e.g. ~/.naosdk/' -r -F
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "install"
complete -c pepsi -n "__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from shell" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l profile -r
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l no-sdk-installation -d 'Do not update nor install SDK'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l no-build -d 'Do not build before uploading'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l no-restart -d 'Do not restart HULK nor HULA service after uploading'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l no-clean -d 'Do not remove existing remote files during uploading'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l no-communication -d 'Do not enable communication'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l skip-os-check -d 'Skip the OS version check'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -l remote -d 'Use a remote machine for compilation, see ./scripts/remote for details'
complete -c pepsi -n "__fish_seen_subcommand_from upload" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available networks'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "set" -d 'Set active network'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "status" -d 'Show current network status'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List available networks'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "set" -d 'Set active network'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "status" -d 'Show current network status'
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "analyze" -d 'Analyze source code'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "aliveness" -d 'Get aliveness information from NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "build" -d 'Builds the code for a target'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "check" -d 'Checks the code with cargo check'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "clippy" -d 'Checks the code with cargo clippy'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "communication" -d 'Enable/disable communication'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "completions" -d 'Generates shell completion files'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "gammaray" -d 'Flash a HULKs-OS image to NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "hulk" -d 'Control the HULK service'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "location" -d 'Control the configured location'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "logs" -d 'Logging on the NAO'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "playernumber" -d 'Change player numbers of the NAOs in local parameters'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "ping" -d 'Ping NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "postgame" -d 'Disable NAOs after a game (downloads logs, unsets wireless network, etc.)'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "poweroff" -d 'Power NAOs off'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "pregame" -d 'Get NAOs ready for a game (sets player numbers, uploads, sets wireless network, etc.)'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "reboot" -d 'Reboot NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "recording" -d 'Set cycler instances to be recorded'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "run" -d 'Runs the code for a target'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "sdk" -d 'Manage the NAO SDK'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "shell" -d 'Opens a command line shell to a NAO'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "upload" -d 'Upload the code to NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "wireless" -d 'Control wireless network on the NAO'
complete -c pepsi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from aliveness; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from clippy; and not __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from gammaray; and not __fish_seen_subcommand_from hulk; and not __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from playernumber; and not __fish_seen_subcommand_from ping; and not __fish_seen_subcommand_from postgame; and not __fish_seen_subcommand_from poweroff; and not __fish_seen_subcommand_from pregame; and not __fish_seen_subcommand_from reboot; and not __fish_seen_subcommand_from recording; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from upload; and not __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest" -f -a "dump-contexts"
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from dump-contexts; and not __fish_seen_subcommand_from dump-latest" -f -a "dump-latest"
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable" -f -a "enable"
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from communication; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable" -f -a "disable"
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status" -f -a "list" -d 'List all available locations'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status" -f -a "set" -d 'Set location for repository'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from location; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status" -f -a "status" -d 'Get currently configured locations'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show" -f -a "delete" -d 'Delete logs on the NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show" -f -a "download" -d 'Download logs from the NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logs; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from download; and not __fish_seen_subcommand_from show" -f -a "show" -d 'Show logs from NAOs'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from sdk; and not __fish_seen_subcommand_from install" -f -a "install"
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status" -f -a "list" -d 'List available networks'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status" -f -a "set" -d 'Set active network'
complete -c pepsi -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from wireless; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from status" -f -a "status" -d 'Show current network status'
complete -c pepsi -n "__fish_seen_subcommand_from aliveness" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from gammaray" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from hulk" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from delete" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from downloads" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from logs; and __fish_seen_subcommand_from show" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from postgame" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from poweroff" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from reboot" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from shell" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from upload" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from list" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from set" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from wireless; and __fish_seen_subcommand_from status" -f -a "(pepsi completions --complete-naos fish)"
complete -c pepsi -n "__fish_seen_subcommand_from playernumber" -f -a "(pepsi completions --complete-assignments fish)"
complete -c pepsi -n "__fish_seen_subcommand_from pregame" -f -a "(pepsi completions --complete-assignments fish)"
